// <auto-generated>
// [T4] build 2024-10-08 10:23:26Z(UTC)
// </auto-generated>
#nullable enable

using System;
using System.Diagnostics;

namespace ContentTypeTextNet.Pe.Library.DependencyInjection
{
    partial class DiConstructorCache
    {
        private delegate object DiConstructorCacheP1(object? p1);
        private delegate object DiConstructorCacheP2(object? p1, object? p2);
        private delegate object DiConstructorCacheP3(object? p1, object? p2, object? p3);
        private delegate object DiConstructorCacheP4(object? p1, object? p2, object? p3, object? p4);
        private delegate object DiConstructorCacheP5(object? p1, object? p2, object? p3, object? p4, object? p5);
        private delegate object DiConstructorCacheP6(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6);
        private delegate object DiConstructorCacheP7(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7);
        private delegate object DiConstructorCacheP8(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8);
        private delegate object DiConstructorCacheP9(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9);
        private delegate object DiConstructorCacheP10(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10);
        private delegate object DiConstructorCacheP11(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10, object? p11);
        private delegate object DiConstructorCacheP12(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10, object? p11, object? p12);
        private delegate object DiConstructorCacheP13(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10, object? p11, object? p12, object? p13);
        private delegate object DiConstructorCacheP14(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10, object? p11, object? p12, object? p13, object? p14);
        private delegate object DiConstructorCacheP15(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10, object? p11, object? p12, object? p13, object? p14, object? p15);
        private delegate object DiConstructorCacheP16(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10, object? p11, object? p12, object? p13, object? p14, object? p15, object? p16);
        private delegate object DiConstructorCacheP17(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10, object? p11, object? p12, object? p13, object? p14, object? p15, object? p16, object? p17);
        private delegate object DiConstructorCacheP18(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10, object? p11, object? p12, object? p13, object? p14, object? p15, object? p16, object? p17, object? p18);
        private delegate object DiConstructorCacheP19(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10, object? p11, object? p12, object? p13, object? p14, object? p15, object? p16, object? p17, object? p18, object? p19);
        private delegate object DiConstructorCacheP20(object? p1, object? p2, object? p3, object? p4, object? p5, object? p6, object? p7, object? p8, object? p9, object? p10, object? p11, object? p12, object? p13, object? p14, object? p15, object? p16, object? p17, object? p18, object? p19, object? p20);

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HAA0301:Closure Allocation Source", Justification = "<保留中>")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HAA0302:Display class allocation to capture closure", Justification = "<保留中>")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HAA0101:Array allocation for params parameter", Justification = "<保留中>")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HAA0601:Value type to reference type conversion causing boxing allocation", Justification = "<保留中>")]
        private Func<object?[], object> CreateCore(object?[] parameters)
        {
            switch(ParameterInfoItems.Count) {
                case 1: {
                        var creator = CreateFunction<DiConstructorCacheP1>();
                        return p => creator(p[0]);
                    }
                case 2: {
                        var creator = CreateFunction<DiConstructorCacheP2>();
                        return p => creator(p[0], p[1]);
                    }
                case 3: {
                        var creator = CreateFunction<DiConstructorCacheP3>();
                        return p => creator(p[0], p[1], p[2]);
                    }
                case 4: {
                        var creator = CreateFunction<DiConstructorCacheP4>();
                        return p => creator(p[0], p[1], p[2], p[3]);
                    }
                case 5: {
                        var creator = CreateFunction<DiConstructorCacheP5>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4]);
                    }
                case 6: {
                        var creator = CreateFunction<DiConstructorCacheP6>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5]);
                    }
                case 7: {
                        var creator = CreateFunction<DiConstructorCacheP7>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6]);
                    }
                case 8: {
                        var creator = CreateFunction<DiConstructorCacheP8>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7]);
                    }
                case 9: {
                        var creator = CreateFunction<DiConstructorCacheP9>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8]);
                    }
                case 10: {
                        var creator = CreateFunction<DiConstructorCacheP10>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9]);
                    }
                case 11: {
                        var creator = CreateFunction<DiConstructorCacheP11>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10]);
                    }
                case 12: {
                        var creator = CreateFunction<DiConstructorCacheP12>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11]);
                    }
                case 13: {
                        var creator = CreateFunction<DiConstructorCacheP13>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12]);
                    }
                case 14: {
                        var creator = CreateFunction<DiConstructorCacheP14>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13]);
                    }
                case 15: {
                        var creator = CreateFunction<DiConstructorCacheP15>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13], p[14]);
                    }
                case 16: {
                        var creator = CreateFunction<DiConstructorCacheP16>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13], p[14], p[15]);
                    }
                case 17: {
                        var creator = CreateFunction<DiConstructorCacheP17>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13], p[14], p[15], p[16]);
                    }
                case 18: {
                        var creator = CreateFunction<DiConstructorCacheP18>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13], p[14], p[15], p[16], p[17]);
                    }
                case 19: {
                        var creator = CreateFunction<DiConstructorCacheP19>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13], p[14], p[15], p[16], p[17], p[18]);
                    }
                case 20: {
                        var creator = CreateFunction<DiConstructorCacheP20>();
                        return p => creator(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13], p[14], p[15], p[16], p[17], p[18], p[19]);
                    }

                default:
                    Debug.WriteLine("パラメータ数ガン上げ: 20 < {0}", ParameterInfoItems.Count);
                    return ConstructorInfo.Invoke;
            }
        }
    }
}
