
// <auto-generated>
// [T4] build 2022-03-22 14:50:07Z(UTC)
// </auto-generated>

namespace ContentTypeTextNet.Pe.Bridge.Models.Data
{
    /// <summary>
    /// ランチャーアイテムID。
    /// </summary>
    public readonly record struct LauncherItemId: System.IEquatable<LauncherItemId>
    {
        /// <summary>
        /// 生成。
        /// </summary>
        public LauncherItemId(System.Guid rawId)
        {
            Id = rawId;
        }

        /// <summary>
        /// 生成。
        /// </summary>
        public LauncherItemId(LauncherItemId id)
        {
            Id = id.Id;
        }

        #region property

        /// <summary>
        /// 生ID。
        /// </summary>
        public System.Guid Id { get; }

        #endregion

        #region IEquatable

        public bool Equals(LauncherItemId other)
        {
            return Id == other.Id;
        }

        #endregion

        #region object

        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }

        #endregion
    }
}
