
// <auto-generated>
// [T4] build 2022-03-26 13:19:51Z(UTC)
// </auto-generated>
using System.Data;
using Dapper;
using ContentTypeTextNet.Pe.Main.Models.Database;
using ContentTypeTextNet.Pe.Bridge.Models.Data;

namespace ContentTypeTextNet.Pe.Main.Models.Applications
{
    partial class ApplicationDatabaseImplementation
    {
        #region define

        private class LauncherItemIdHandler: SqlMapper.TypeHandler<LauncherItemId>
        {
            #region TypeHandler

            public override void SetValue(IDbDataParameter parameter, LauncherItemId value)
            {
                parameter.Value = value.Id.ToString("D");
            }

            public override LauncherItemId Parse(object value)
            {

                var s = (string)value;
                if(s != null) {
                    if(LauncherItemId.TryParse(s, out var ret)) {
                        return ret;
                    }
                }

                return LauncherItemId.Empty;
            }

            #endregion
        }
        private class CredentialIdIdHandler: SqlMapper.TypeHandler<CredentialIdId>
        {
            #region TypeHandler

            public override void SetValue(IDbDataParameter parameter, CredentialIdId value)
            {
                parameter.Value = value.Id.ToString("D");
            }

            public override CredentialIdId Parse(object value)
            {

                var s = (string)value;
                if(s != null) {
                    if(CredentialIdId.TryParse(s, out var ret)) {
                        return ret;
                    }
                }

                return CredentialIdId.Empty;
            }

            #endregion
        }
        private class LauncherToolbarIdHandler: SqlMapper.TypeHandler<LauncherToolbarId>
        {
            #region TypeHandler

            public override void SetValue(IDbDataParameter parameter, LauncherToolbarId value)
            {
                parameter.Value = value.Id.ToString("D");
            }

            public override LauncherToolbarId Parse(object value)
            {

                var s = (string)value;
                if(s != null) {
                    if(LauncherToolbarId.TryParse(s, out var ret)) {
                        return ret;
                    }
                }

                return LauncherToolbarId.Empty;
            }

            #endregion
        }
        private class LauncherGroupIdHandler: SqlMapper.TypeHandler<LauncherGroupId>
        {
            #region TypeHandler

            public override void SetValue(IDbDataParameter parameter, LauncherGroupId value)
            {
                parameter.Value = value.Id.ToString("D");
            }

            public override LauncherGroupId Parse(object value)
            {

                var s = (string)value;
                if(s != null) {
                    if(LauncherGroupId.TryParse(s, out var ret)) {
                        return ret;
                    }
                }

                return LauncherGroupId.Empty;
            }

            #endregion
        }

        #endregion


        static ApplicationDatabaseImplementation()
        {
            SqlMapper.AddTypeHandler(typeof(LauncherItemId), new LauncherItemIdHandler());
            SqlMapper.AddTypeHandler(typeof(CredentialIdId), new CredentialIdIdHandler());
            SqlMapper.AddTypeHandler(typeof(LauncherToolbarId), new LauncherToolbarIdHandler());
            SqlMapper.AddTypeHandler(typeof(LauncherGroupId), new LauncherGroupIdHandler());
        }
    }
}
