//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeMain.Properties {
	using System;
	
	
	/// <summary>
	///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
	/// </summary>
	// このクラスは StronglyTypedResourceBuilder クラスが ResGen
	// または Visual Studio のようなツールを使用して自動生成されました。
	// メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
	// ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Images {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Images() {
		}
		
		/// <summary>
		///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeMain.Properties.Images", typeof(Images).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
		///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Add {
			get {
				object obj = ResourceManager.GetObject("Add", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap AddItem {
			get {
				object obj = ResourceManager.GetObject("AddItem", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Icon App {
			get {
				object obj = ResourceManager.GetObject("App", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Changelog {
			get {
				object obj = ResourceManager.GetObject("Changelog", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Clear {
			get {
				object obj = ResourceManager.GetObject("Clear", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap ClipboardText {
			get {
				object obj = ResourceManager.GetObject("ClipboardText", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Close {
			get {
				object obj = ResourceManager.GetObject("Close", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Comment {
			get {
				object obj = ResourceManager.GetObject("Comment", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Config {
			get {
				object obj = ResourceManager.GetObject("Config", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap CustomColor {
			get {
				object obj = ResourceManager.GetObject("CustomColor", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Dir {
			get {
				object obj = ResourceManager.GetObject("Dir", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Disk {
			get {
				object obj = ResourceManager.GetObject("Disk", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Down {
			get {
				object obj = ResourceManager.GetObject("Down", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Error {
			get {
				object obj = ResourceManager.GetObject("Error", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap File {
			get {
				object obj = ResourceManager.GetObject("File", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Filter {
			get {
				object obj = ResourceManager.GetObject("Filter", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Find {
			get {
				object obj = ResourceManager.GetObject("Find", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Finder {
			get {
				object obj = ResourceManager.GetObject("Finder", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Flag {
			get {
				object obj = ResourceManager.GetObject("Flag", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Font {
			get {
				object obj = ResourceManager.GetObject("Font", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap FontStyle {
			get {
				object obj = ResourceManager.GetObject("FontStyle", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Group {
			get {
				object obj = ResourceManager.GetObject("Group", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Help {
			get {
				object obj = ResourceManager.GetObject("Help", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Information {
			get {
				object obj = ResourceManager.GetObject("Information", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Kill {
			get {
				object obj = ResourceManager.GetObject("Kill", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Lock {
			get {
				object obj = ResourceManager.GetObject("Lock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Log {
			get {
				object obj = ResourceManager.GetObject("Log", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Name {
			get {
				object obj = ResourceManager.GetObject("Name", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Note {
			get {
				object obj = ResourceManager.GetObject("Note", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap NoteBody {
			get {
				object obj = ResourceManager.GetObject("NoteBody", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap NoteTitle {
			get {
				object obj = ResourceManager.GetObject("NoteTitle", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Icon NotFound {
			get {
				object obj = ResourceManager.GetObject("NotFound", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap NotImpl {
			get {
				object obj = ResourceManager.GetObject("NotImpl", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap OpenDir {
			get {
				object obj = ResourceManager.GetObject("OpenDir", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Pin {
			get {
				object obj = ResourceManager.GetObject("Pin", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Refresh {
			get {
				object obj = ResourceManager.GetObject("Refresh", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Remove {
			get {
				object obj = ResourceManager.GetObject("Remove", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Save {
			get {
				object obj = ResourceManager.GetObject("Save", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap SideContract {
			get {
				object obj = ResourceManager.GetObject("SideContract", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap SideExpand {
			get {
				object obj = ResourceManager.GetObject("SideExpand", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap SystemEnvironment {
			get {
				object obj = ResourceManager.GetObject("SystemEnvironment", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Tag {
			get {
				object obj = ResourceManager.GetObject("Tag", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Toolbar {
			get {
				object obj = ResourceManager.GetObject("Toolbar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Icon ToolbarMain {
			get {
				object obj = ResourceManager.GetObject("ToolbarMain", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Unlock {
			get {
				object obj = ResourceManager.GetObject("Unlock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Up {
			get {
				object obj = ResourceManager.GetObject("Up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Update {
			get {
				object obj = ResourceManager.GetObject("Update", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Icon URI {
			get {
				object obj = ResourceManager.GetObject("URI", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Warning {
			get {
				object obj = ResourceManager.GetObject("Warning", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap WindowList {
			get {
				object obj = ResourceManager.GetObject("WindowList", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap WindowLoad {
			get {
				object obj = ResourceManager.GetObject("WindowLoad", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Windows {
			get {
				object obj = ResourceManager.GetObject("Windows", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap WindowSave {
			get {
				object obj = ResourceManager.GetObject("WindowSave", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
