//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18408
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeMain.Properties {
	using System;
	
	
	/// <summary>
	///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
	/// </summary>
	// このクラスは StronglyTypedResourceBuilder クラスが ResGen
	// または Visual Studio のようなツールを使用して自動生成されました。
	// メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
	// ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Images {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Images() {
		}
		
		/// <summary>
		///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeMain.Properties.Images", typeof(Images).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
		///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Add {
			get {
				object obj = ResourceManager.GetObject("Add", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Dir {
			get {
				object obj = ResourceManager.GetObject("Dir", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap File {
			get {
				object obj = ResourceManager.GetObject("File", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Filter {
			get {
				object obj = ResourceManager.GetObject("Filter", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Find {
			get {
				object obj = ResourceManager.GetObject("Find", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap NotImpl {
			get {
				object obj = ResourceManager.GetObject("NotImpl", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Icon Pe {
			get {
				object obj = ResourceManager.GetObject("Pe", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		public static System.Drawing.Bitmap Remove {
			get {
				object obj = ResourceManager.GetObject("Remove", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
