//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentTypeTextNet.Pe.PeMain.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentTypeTextNet.Pe.PeMain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon Icon_App {
            get {
                object obj = ResourceManager.GetObject("Icon_App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Add {
            get {
                object obj = ResourceManager.GetObject("Image_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_AddItem {
            get {
                object obj = ResourceManager.GetObject("Image_AddItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Applications {
            get {
                object obj = ResourceManager.GetObject("Image_Applications", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Changelog {
            get {
                object obj = ResourceManager.GetObject("Image_Changelog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Clear {
            get {
                object obj = ResourceManager.GetObject("Image_Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Clipboard {
            get {
                object obj = ResourceManager.GetObject("Image_Clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_ClipboardCopy {
            get {
                object obj = ResourceManager.GetObject("Image_ClipboardCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_ClipboardFile {
            get {
                object obj = ResourceManager.GetObject("Image_ClipboardFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_ClipboardHtml {
            get {
                object obj = ResourceManager.GetObject("Image_ClipboardHtml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_ClipboardImage {
            get {
                object obj = ResourceManager.GetObject("Image_ClipboardImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_ClipboardRichTextFormat {
            get {
                object obj = ResourceManager.GetObject("Image_ClipboardRichTextFormat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_ClipboardText {
            get {
                object obj = ResourceManager.GetObject("Image_ClipboardText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Close {
            get {
                object obj = ResourceManager.GetObject("Image_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Comment {
            get {
                object obj = ResourceManager.GetObject("Image_Comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Config {
            get {
                object obj = ResourceManager.GetObject("Image_Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_CustomColor {
            get {
                object obj = ResourceManager.GetObject("Image_CustomColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Debug {
            get {
                object obj = ResourceManager.GetObject("Image_Debug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Dir {
            get {
                object obj = ResourceManager.GetObject("Image_Dir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Disk {
            get {
                object obj = ResourceManager.GetObject("Image_Disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Down {
            get {
                object obj = ResourceManager.GetObject("Image_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_File {
            get {
                object obj = ResourceManager.GetObject("Image_File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Filter {
            get {
                object obj = ResourceManager.GetObject("Image_Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Find {
            get {
                object obj = ResourceManager.GetObject("Image_Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Finder {
            get {
                object obj = ResourceManager.GetObject("Image_Finder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Flag {
            get {
                object obj = ResourceManager.GetObject("Image_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Font {
            get {
                object obj = ResourceManager.GetObject("Image_Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_FontStyle {
            get {
                object obj = ResourceManager.GetObject("Image_FontStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Group {
            get {
                object obj = ResourceManager.GetObject("Image_Group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Help {
            get {
                object obj = ResourceManager.GetObject("Image_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Kill {
            get {
                object obj = ResourceManager.GetObject("Image_Kill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Lock {
            get {
                object obj = ResourceManager.GetObject("Image_Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Log {
            get {
                object obj = ResourceManager.GetObject("Image_Log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Name {
            get {
                object obj = ResourceManager.GetObject("Image_Name", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Note {
            get {
                object obj = ResourceManager.GetObject("Image_Note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_NoteBody {
            get {
                object obj = ResourceManager.GetObject("Image_NoteBody", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_NoteTitle {
            get {
                object obj = ResourceManager.GetObject("Image_NoteTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_NotImpl {
            get {
                object obj = ResourceManager.GetObject("Image_NotImpl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_OpenDir {
            get {
                object obj = ResourceManager.GetObject("Image_OpenDir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Pin {
            get {
                object obj = ResourceManager.GetObject("Image_Pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Refresh {
            get {
                object obj = ResourceManager.GetObject("Image_Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Remove {
            get {
                object obj = ResourceManager.GetObject("Image_Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_ReplaceSkin {
            get {
                object obj = ResourceManager.GetObject("Image_ReplaceSkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Save {
            get {
                object obj = ResourceManager.GetObject("Image_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_SideContract {
            get {
                object obj = ResourceManager.GetObject("Image_SideContract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_SideExpand {
            get {
                object obj = ResourceManager.GetObject("Image_SideExpand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_SystemEnvironment {
            get {
                object obj = ResourceManager.GetObject("Image_SystemEnvironment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Tag {
            get {
                object obj = ResourceManager.GetObject("Image_Tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Toolbar {
            get {
                object obj = ResourceManager.GetObject("Image_Toolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Unlock {
            get {
                object obj = ResourceManager.GetObject("Image_Unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Up {
            get {
                object obj = ResourceManager.GetObject("Image_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Update {
            get {
                object obj = ResourceManager.GetObject("Image_Update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_WindowList {
            get {
                object obj = ResourceManager.GetObject("Image_WindowList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_WindowLoad {
            get {
                object obj = ResourceManager.GetObject("Image_WindowLoad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_Windows {
            get {
                object obj = ResourceManager.GetObject("Image_Windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Image_WindowSave {
            get {
                object obj = ResourceManager.GetObject("Image_WindowSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   select
        ///    count(*) NUM
        ///from
        ///    SQLITE_MASTER
        ///where
        ///    NAME = :table_name
        ///    and
        ///    TYPE = &apos;table&apos;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_CheckTable {
            get {
                return ResourceManager.GetString("SQL_CheckTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   create table M_NOTE (
        ///    NOTE_ID      integer  primary key,
        ///    CMN_ENABLED  integer  not null,
        ///    CMN_CREATE   text     not null,
        ///    CMN_UPDATE   text     not null,
        ///    NOTE_TITLE   text,
        ///    NOTE_TYPE    integer  not null
        ///)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_CreateNoteMasterTable {
            get {
                return ResourceManager.GetString("SQL_CreateNoteMasterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   create table T_NOTE_STYLE (
        ///    NOTE_ID         integer  primary key,
        ///    CMN_CREATE      text     not null,
        ///    CMN_UPDATE      text     not null,
        ///    FONT_FAMILY     text     not null,
        ///    FONT_SIZE       real     not null,
        ///    FONT_ITALIC     integer  not null,
        ///    FONT_BOLD       integer  not null,
        ///    COLOR_FORE      text     not null,
        ///    COLOR_BACK      text     not null,
        ///    WINDOW_VISIBLED integer  not null,
        ///    WINDOW_LOCKED   integer  not null,
        ///    WINDOW_TOPMOST  integer  not null,
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_CreateNoteStyleTransactionTable {
            get {
                return ResourceManager.GetString("SQL_CreateNoteStyleTransactionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   create table T_NOTE (
        ///    NOTE_ID      integer  primary key,
        ///    CMN_CREATE   text     not null,
        ///    CMN_UPDATE   text     not null,
        ///    NOTE_BODY    text
        ///)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_CreateNoteTransactionTable {
            get {
                return ResourceManager.GetString("SQL_CreateNoteTransactionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   create table M_VERSION
        ///(
        ///    NAME     text primary key,
        ///    VERSION  integer not null
        ///)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_CreateVersionMasterTable {
            get {
                return ResourceManager.GetString("SQL_CreateVersionMasterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   update
        ///	M_NOTE
        ///set
        ///	CMN_ENABLED = :enabled,
        ///	CMN_UPDATE  = :update
        ///where
        ///	({ID_LIST})
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_EnabledSwitch {
            get {
                return ResourceManager.GetString("SQL_EnabledSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select
        ///    coalesce(max({id_column_name}), 0) MAX_ID,
        ///    coalesce(min({id_column_name}), 0) MIN_ID
        ///from
        ///    {table_name}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_GetId {
            get {
                return ResourceManager.GetString("SQL_GetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select
        ///	CMN_ENABLED,
        ///	NOTE_ID,
        ///	NOTE_TITLE,
        ///	NOTE_TYPE,
        ///	NOTE_BODY,
        ///	WINDOW_VISIBLED,
        ///	WINDOW_LOCKED,
        ///	WINDOW_TOPMOST,
        ///	WINDOW_COMPACT,
        ///	WINDOW_POS_X,
        ///	WINDOW_POS_Y,
        ///	WINDOW_SIZE_W,
        ///	WINDOW_SIZE_H,
        ///	FONT_FAMILY,
        ///	FONT_SIZE,
        ///	FONT_ITALIC,
        ///	FONT_BOLD,
        ///	COLOR_FORE,
        ///	COLOR_BACK
        ///from
        ///	M_NOTE
        ///	inner join T_NOTE using(NOTE_ID)
        ///	inner join T_NOTE_STYLE using(NOTE_ID)
        ///order by
        ///	M_NOTE.CMN_CREATE
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SQL_GetNoteItemList {
            get {
                return ResourceManager.GetString("SQL_GetNoteItemList", resourceCulture);
            }
        }
    }
}
