
// <auto-generated>
// [T4] build 2022-03-22 14:57:08Z(UTC)
// </auto-generated>
using System.Data;
using Dapper;
using ContentTypeTextNet.Pe.Main.Models.Database;

namespace ContentTypeTextNet.Pe.Main.Models.Data
{
    internal class ApplicationDatabaseLauncherItemIdHandler: GuidTypeHandler
    { }
}

namespace ContentTypeTextNet.Pe.Main.Models.Applications
{
    partial class ApplicationDatabaseImplementation
    {
        static ApplicationDatabaseImplementation()
        {
            SqlMapper.AddTypeHandler(typeof(System.Guid), new ContentTypeTextNet.Pe.Main.Models.Data.ApplicationDatabaseLauncherItemIdHandler());
        }
    }
}
