
// <auto-generated>
// [T4] build 2022-03-23 13:33:04Z(UTC)
// </auto-generated>
using System.Data;
using Dapper;
using ContentTypeTextNet.Pe.Main.Models.Database;
using ContentTypeTextNet.Pe.Bridge.Models.Data;

namespace ContentTypeTextNet.Pe.Main.Models.Data
{
    internal class ApplicationDatabaseLauncherItemIdHandler: SqlMapper.TypeHandler<LauncherItemId>
    {
        #region TypeHandler

        public override void SetValue(IDbDataParameter parameter, LauncherItemId value)
        {
            parameter.Value = value.Id.ToString("D");
        }

        public override LauncherItemId Parse(object value)
        {

            var s = (string)value;
            if(s != null) {
                if(LauncherItemId.TryParse(s, out var ret)) {
                    return ret;
                }
            }

            return LauncherItemId.Empty;
        }

        #endregion
    }
}

namespace ContentTypeTextNet.Pe.Main.Models.Applications
{
    partial class ApplicationDatabaseImplementation
    {
        static ApplicationDatabaseImplementation()
        {
            SqlMapper.AddTypeHandler(typeof(LauncherItemId), new ContentTypeTextNet.Pe.Main.Models.Data.ApplicationDatabaseLauncherItemIdHandler());
        }
    }
}
