//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentTypeTextNet.Pe.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentTypeTextNet.Pe.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;FlowDocument
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///&gt;
        ///  &lt;FlowDocument.Resources&gt;
        ///    &lt;Style x:Key=&quot;Header&quot; TargetType=&quot;Paragraph&quot;&gt;
        ///      &lt;Setter Property=&quot;Margin&quot; Value=&quot;0, 20, 0, 10&quot; /&gt;
        ///      &lt;Setter Property=&quot;FontSize&quot; Value=&quot;16pt&quot; /&gt;
        ///      &lt;Setter Property=&quot;FontWeight&quot; Value=&quot;Bold&quot; /&gt;
        ///    &lt;/Style&gt;
        ///  &lt;/FlowDocument.Resources&gt;
        ///
        ///  &lt;Paragraph
        ///    FontSize=&quot;20pt&quot;
        ///    FontWeight=&quot;Bold&quot;
        ///    TextDecorations=&quot;Und [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_Accept_AcceptDocument {
            get {
                return ResourceManager.GetString("File_Accept_AcceptDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SyntaxDefinition xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot; name=&quot;EnvVar_Update&quot;&gt;
        ///	&lt;!--TODO:キーと値で分離--&gt;
        ///	&lt;Color name=&quot;Key&quot; fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot; /&gt;
        ///	&lt;Color name=&quot;Variable&quot; foreground=&quot;Maroon&quot; /&gt;
        ///	&lt;RuleSet ignoreCase=&quot;true&quot;&gt;
        ///		&lt;Rule color=&quot;Key&quot;&gt;
        ///			\w+
        ///		&lt;/Rule&gt;
        ///	&lt;/RuleSet&gt;
        ///&lt;/SyntaxDefinition&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_Highlighting_EnvironmentVariable_Merge {
            get {
                return ResourceManager.GetString("File_Highlighting_EnvironmentVariable_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SyntaxDefinition xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot; name=&quot;EnvVar_Remove&quot;&gt;
        ///	&lt;!--TODO:キーに限定--&gt;
        ///	&lt;Color name=&quot;Key&quot; fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot; /&gt;
        ///	&lt;RuleSet ignoreCase=&quot;true&quot;&gt;
        ///		&lt;Rule color=&quot;Key&quot;&gt;
        ///			\w+
        ///		&lt;/Rule&gt;
        ///	&lt;/RuleSet&gt;
        ///&lt;/SyntaxDefinition&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_Highlighting_EnvironmentVariable_Remove {
            get {
                return ResourceManager.GetString("File_Highlighting_EnvironmentVariable_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SyntaxDefinition xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot; name=&quot;EnvVar_Remove&quot;&gt;
        ///	&lt;!--きちんとする--&gt;
        ///	&lt;Color name=&quot;Key&quot; /&gt;
        ///	&lt;RuleSet ignoreCase=&quot;true&quot;&gt;
        ///		&lt;Rule color=&quot;Key&quot;&gt;
        ///			\w+
        ///		&lt;/Rule&gt;
        ///	&lt;/RuleSet&gt;
        ///
        ///&lt;/SyntaxDefinition&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_Highlighting_Tag {
            get {
                return ResourceManager.GetString("File_Highlighting_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用許諾  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Accept_Caption {
            get {
                return ResourceManager.GetString("String_Accept_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Accept_Command_Affirmative {
            get {
                return ResourceManager.GetString("String_Accept_Command_Affirmative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用しない(N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Accept_Command_Negative {
            get {
                return ResourceManager.GetString("String_Accept_Command_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Accept_PlaceHolder_Affirmative {
            get {
                return ResourceManager.GetString("String_Accept_PlaceHolder_Affirmative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Accept_PlaceHolder_Negative {
            get {
                return ResourceManager.GetString("String_Accept_PlaceHolder_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報(_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_About {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_About_Help {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_About_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報(_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_About_Version {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Command {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Exit {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノート(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Note {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最後面へ移動(_B) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Note_Bottom {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Note_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小化(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Note_Compact {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Note_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Note_Create {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Note_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非表示(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Note_Hidden {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Note_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面へ移動(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Note_Topmost {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Note_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示中(_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Note_Visible {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Note_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pe 設定(_S) ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Setting {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツールバー(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_AppManager_Menu_Toolbar {
            get {
                return ResourceManager.GetString("String_AppManager_Menu_Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンドランチャー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Command_Caption {
            get {
                return ResourceManager.GetString("String_Command_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンドを実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Command_Tooltip_Execute {
            get {
                return ResourceManager.GetString("String_Command_Tooltip_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Common_Command_Cancel {
            get {
                return ResourceManager.GetString("String_Common_Command_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Common_Command_Close {
            get {
                return ResourceManager.GetString("String_Common_Command_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Common_Command_Ok {
            get {
                return ResourceManager.GetString("String_Common_Command_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Common_Tooltip_Clear {
            get {
                return ResourceManager.GetString("String_Common_Tooltip_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレクトリ選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Common_Tooltip_SelectDirectory {
            get {
                return ResourceManager.GetString("String_Common_Tooltip_SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Common_Tooltip_SelectFile {
            get {
                return ResourceManager.GetString("String_Common_Tooltip_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_EnvironmentValieableEditor_Label_Merge {
            get {
                return ResourceManager.GetString("String_EnvironmentValieableEditor_Label_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_EnvironmentValieableEditor_Label_Remove {
            get {
                return ResourceManager.GetString("String_EnvironmentValieableEditor_Label_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${ITEM} を指定して実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ExtendsExecute_Caption {
            get {
                return ResourceManager.GetString("String_ExtendsExecute_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ExtendsExecute_Command_Execute {
            get {
                return ResourceManager.GetString("String_ExtendsExecute_Command_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ExtendsExecute_Label_Command {
            get {
                return ResourceManager.GetString("String_ExtendsExecute_Label_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   環境変数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ExtendsExecute_Label_EnvironmentVariables {
            get {
                return ResourceManager.GetString("String_ExtendsExecute_Label_EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ExtendsExecute_Label_EnvironmentVariables_Edit {
            get {
                return ResourceManager.GetString("String_ExtendsExecute_Label_EnvironmentVariables_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ExtendsExecute_Label_Options {
            get {
                return ResourceManager.GetString("String_ExtendsExecute_Label_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ExtendsExecute_Label_Others {
            get {
                return ResourceManager.GetString("String_ExtendsExecute_Label_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ExtendsExecute_Label_Others_RunAdmin {
            get {
                return ResourceManager.GetString("String_ExtendsExecute_Label_Others_RunAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準入出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ExtendsExecute_Label_Others_StandardInputOutput {
            get {
                return ResourceManager.GetString("String_ExtendsExecute_Label_Others_StandardInputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業ディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ExtendsExecute_Label_WorkDirectory {
            get {
                return ResourceManager.GetString("String_ExtendsExecute_Label_WorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランチャーアイテム取り込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ImportPrograms_Caption {
            get {
                return ResourceManager.GetString("String_ImportPrograms_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取り込み(_I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_ImportPrograms_Command_Import {
            get {
                return ResourceManager.GetString("String_ImportPrograms_Command_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動設定グループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherGroup_ImportItem_Name {
            get {
                return ResourceManager.GetString("String_LauncherGroup_ImportItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいグループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherGroup_NewItem_Name {
            get {
                return ResourceManager.GetString("String_LauncherGroup_NewItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいアイテム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItem_NewItem_Name {
            get {
                return ResourceManager.GetString("String_LauncherItem_NewItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Comment_Header {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Comment_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共通 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Common_Header {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Common_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Common_Label_Code {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Common_Label_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Common_Label_Id {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Common_Label_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   種別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Common_Label_Kind {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Common_Label_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Common_Label_Name {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Common_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Common_Label_Others {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Common_Label_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンドランチャーで使用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Common_Label_Others_UseCommandLauncher {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Common_Label_Others_UseCommandLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイコン選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Common_Tooltip_SelectIcon {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Common_Tooltip_SelectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Common_Tooltip_SelectImage {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Common_Tooltip_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   環境変数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_EnvironmentVariable_Header {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_EnvironmentVariable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準入出力を使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_File_Command_IsEnable_StandardInputOutpu {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_File_Command_IsEnable_StandardInputOutpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   環境変数を編集する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_File_Command_IsEnabled_CustomEnvironmentVariable {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_File_Command_IsEnabled_CustomEnvironmentVaria" +
                        "ble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者として実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_File_Command_RunAdministrator {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_File_Command_RunAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_File_Header {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_File_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_File_Label_Options {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_File_Label_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_File_Label_Others {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_File_Label_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_File_Label_Path {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_File_Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_File_Label_WorkDirectory {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_File_Label_WorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストアアプリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_StoreApp_Header {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_StoreApp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_StoreApp_Label_Options {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_StoreApp_Label_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロトコル/エイリアス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_StoreApp_Label_ProtocolAlias {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_StoreApp_Label_ProtocolAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeControl_Tag_Header {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeControl_Tag_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${ITEM} を編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItemCustomizeWindow_Caption {
            get {
                return ResourceManager.GetString("String_LauncherItemCustomizeWindow_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_AppMenu_Groups_Header {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_AppMenu_Groups_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動的に隠す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_AppMenu_Menu_AutoHide {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_AppMenu_Menu_AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_AppMenu_Menu_Close {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_AppMenu_Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_AppMenu_Menu_Topmost {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_AppMenu_Menu_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツールバー位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_AppMenu_Position_Header {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_AppMenu_Position_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Copy_Header {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Copy_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Copy_Menu_Options {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Copy_Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親ディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Copy_Menu_ParentDirectory {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Copy_Menu_ParentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Copy_Menu_Path {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Copy_Menu_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業ディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Copy_Menu_WorkDirectory {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Copy_Menu_WorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Execute_Header {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Execute_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通常実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Execute_Menu_Execute {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Execute_Menu_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定して実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Execute_Menu_ExtendsExecute {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Execute_Menu_ExtendsExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Groups_Header {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Groups_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Open_Header {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Open_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   親ディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Open_Menu_ParentDirectory {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Open_Menu_ParentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業ディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Open_Menu_WorkDirectory {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Open_Menu_WorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Others_Header {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Others_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Others_Menu_Customize {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Others_Menu_Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Others_Menu_Property {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Others_Menu_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Others_Menu_Remove_Confirm {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Others_Menu_Remove_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherToolbar_FileContextMenu_Others_Menu_Remove_Execute {
            get {
                return ResourceManager.GetString("String_LauncherToolbar_FileContextMenu_Others_Menu_Remove_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Busy {
            get {
                return ResourceManager.GetString("String_Note_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Caption_Tooltip_Close {
            get {
                return ResourceManager.GetString("String_Note_Caption_Tooltip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小化切り替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Caption_Tooltip_ToggleCompact {
            get {
                return ResourceManager.GetString("String_Note_Caption_Tooltip_ToggleCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面切り替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Caption_Tooltip_ToggleTopmost {
            get {
                return ResourceManager.GetString("String_Note_Caption_Tooltip_ToggleTopmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーマット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Format_Header {
            get {
                return ResourceManager.GetString("String_Note_Format_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Format_Label_Background {
            get {
                return ResourceManager.GetString("String_Note_Format_Label_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Format_Label_Font {
            get {
                return ResourceManager.GetString("String_Note_Format_Label_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前景 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Format_Label_Foreground {
            get {
                return ResourceManager.GetString("String_Note_Format_Label_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   種別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Format_Label_Kind {
            get {
                return ResourceManager.GetString("String_Note_Format_Label_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Format_Label_Kind_Plain {
            get {
                return ResourceManager.GetString("String_Note_Format_Label_Kind_Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RTF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Format_Label_Kind_RichText {
            get {
                return ResourceManager.GetString("String_Note_Format_Label_Kind_RichText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Format_Label_Layout {
            get {
                return ResourceManager.GetString("String_Note_Format_Label_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   絶対 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Format_Label_Layout_Absolute {
            get {
                return ResourceManager.GetString("String_Note_Format_Label_Layout_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   相対 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Format_Label_Layout_Relative {
            get {
                return ResourceManager.GetString("String_Note_Format_Label_Layout_Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${FROM-KIND} から ${TO-KIND} への変換により一部情報が失われます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_KindChanging_Change {
            get {
                return ResourceManager.GetString("String_Note_KindChanging_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_KindChanging_Command_Convert {
            get {
                return ResourceManager.GetString("String_Note_KindChanging_Command_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを削除してリンク切断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Link_Command_Delete {
            get {
                return ResourceManager.GetString("String_Note_Link_Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルからリンク作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Link_Command_OpenLink {
            get {
                return ResourceManager.GetString("String_Note_Link_Command_OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力内容からリンク作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Link_Command_SaveLink {
            get {
                return ResourceManager.GetString("String_Note_Link_Command_SaveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンク切断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Link_Command_Unlink {
            get {
                return ResourceManager.GetString("String_Note_Link_Command_Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクされています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Link_Linking {
            get {
                return ResourceManager.GetString("String_Note_Link_Linking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクされていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Link_NotLinking {
            get {
                return ResourceManager.GetString("String_Note_Link_NotLinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Operation_Command_Close {
            get {
                return ResourceManager.GetString("String_Note_Operation_Command_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Operation_Command_Copy {
            get {
                return ResourceManager.GetString("String_Note_Operation_Command_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Operation_Command_Remove_Confirm {
            get {
                return ResourceManager.GetString("String_Note_Operation_Command_Remove_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Operation_Command_Remove_Execute {
            get {
                return ResourceManager.GetString("String_Note_Operation_Command_Remove_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Operation_Header {
            get {
                return ResourceManager.GetString("String_Note_Operation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Status_Command_Link {
            get {
                return ResourceManager.GetString("String_Note_Status_Command_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Status_Header {
            get {
                return ResourceManager.GetString("String_Note_Status_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Status_Label_Compact {
            get {
                return ResourceManager.GetString("String_Note_Status_Label_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   固定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Status_Label_Lock {
            get {
                return ResourceManager.GetString("String_Note_Status_Label_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Status_Label_Topmost {
            get {
                return ResourceManager.GetString("String_Note_Status_Label_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右端で折り返す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Note_Status_Label_WordWrap {
            get {
                return ResourceManager.GetString("String_Note_Status_Label_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディスプレイ識別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Screen_Caption {
            get {
                return ResourceManager.GetString("String_Screen_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マウスクリックかキー入力(どれでも)でディスプレイ識別ウィンドウを閉じてください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Screen_Close_Message {
            get {
                return ResourceManager.GetString("String_Screen_Close_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メインディスプレイ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Screen_Primary {
            get {
                return ResourceManager.GetString("String_Screen_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド型ランチャー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Command_Header {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Command_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Command_Label_Find {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Command_Label_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグを検索する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Command_Label_Find_Tag {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Command_Label_Find_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Command_Label_Font {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Command_Label_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイコン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Command_Label_Icon {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Command_Label_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Command_Label_Icon_Big {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Command_Label_Icon_Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Command_Label_Icon_Normal {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Command_Label_Icon_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Command_Label_Icon_Small {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Command_Label_Icon_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Command_Label_Wait {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Command_Label_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   横幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Command_Label_Width {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Command_Label_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   環境から生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Execute_Command_CreateUserIdFromEnvironment {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Execute_Command_CreateUserIdFromEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランダムに生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Execute_Command_CreateUserIdFromRandom {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Execute_Command_CreateUserIdFromRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行環境 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Execute_Header {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Execute_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用統計情報の送信を許可する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Execute_Label_SendUsageStatistics {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Execute_Label_SendUsageStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Execute_Label_UserId {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Execute_Label_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDと使用統計情報について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Execute_UserIdDescription {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Execute_UserIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_General_Header {
            get {
                return ResourceManager.GetString("String_Setting_Generals_General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_General_Label_Language {
            get {
                return ResourceManager.GetString("String_Setting_Generals_General_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_General_Label_Starup {
            get {
                return ResourceManager.GetString("String_Setting_Generals_General_Label_Starup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_General_Label_Starup_Register {
            get {
                return ResourceManager.GetString("String_Setting_Generals_General_Label_Starup_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動待機時間(秒) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_General_Label_Starup_WaitTime {
            get {
                return ResourceManager.GetString("String_Setting_Generals_General_Label_Starup_WaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーバックアップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_General_Label_UserBackupDirectory {
            get {
                return ResourceManager.GetString("String_Setting_Generals_General_Label_UserBackupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Header {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Header {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Color {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Color_Background {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Color_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前景色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Color_Foreground {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Color_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Font {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Layout {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   絶対座標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Layout_Absolute {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Layout_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   相対座標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Layout_Relative {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Layout_Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Title {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Title_Count {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Title_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムスタンプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Title_Timestamp {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Title_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Note_Label_Topmost {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Note_Label_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準入出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_StandardInputOutput_Header {
            get {
                return ResourceManager.GetString("String_Setting_Generals_StandardInputOutput_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_StandardInputOutput_Label_ErrorColor {
            get {
                return ResourceManager.GetString("String_Setting_Generals_StandardInputOutput_Label_ErrorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_StandardInputOutput_Label_ErrorColor_Background {
            get {
                return ResourceManager.GetString("String_Setting_Generals_StandardInputOutput_Label_ErrorColor_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前景色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_StandardInputOutput_Label_ErrorColor_Foreground {
            get {
                return ResourceManager.GetString("String_Setting_Generals_StandardInputOutput_Label_ErrorColor_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_StandardInputOutput_Label_Font {
            get {
                return ResourceManager.GetString("String_Setting_Generals_StandardInputOutput_Label_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_StandardInputOutput_Label_OutputColor {
            get {
                return ResourceManager.GetString("String_Setting_Generals_StandardInputOutput_Label_OutputColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_StandardInputOutput_Label_OutputColor_Background {
            get {
                return ResourceManager.GetString("String_Setting_Generals_StandardInputOutput_Label_OutputColor_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前景色 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_StandardInputOutput_Label_OutputColor_Foreground {
            get {
                return ResourceManager.GetString("String_Setting_Generals_StandardInputOutput_Label_OutputColor_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_StandardInputOutput_Label_Topmost {
            get {
                return ResourceManager.GetString("String_Setting_Generals_StandardInputOutput_Label_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Update_Header {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Update_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Update_Label_UpdateKind {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Update_Label_UpdateKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Update_Label_UpdateKind_Auto {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Update_Label_UpdateKind_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Update_Label_UpdateKind_None {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Update_Label_UpdateKind_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知のみ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Generals_Update_Label_UpdateKind_Notify {
            get {
                return ResourceManager.GetString("String_Setting_Generals_Update_Label_UpdateKind_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   keyboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Keyboard_Header {
            get {
                return ResourceManager.GetString("String_Setting_Keyboard_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   groups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_LauncherGroups_Header {
            get {
                return ResourceManager.GetString("String_Setting_LauncherGroups_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ランチャーアイテム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_LauncherItems_Header {
            get {
                return ResourceManager.GetString("String_Setting_LauncherItems_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムを追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_LauncherItems_Tooltip_Add {
            get {
                return ResourceManager.GetString("String_Setting_LauncherItems_Tooltip_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムを削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_LauncherItems_Tooltip_Remove {
            get {
                return ResourceManager.GetString("String_Setting_LauncherItems_Tooltip_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   toolbars に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_LauncherToolbars_Header {
            get {
                return ResourceManager.GetString("String_Setting_LauncherToolbars_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${ITEM} の標準入出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_Caption {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動スクロール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_Command_AutoScroll {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_Command_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_Command_Clear {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_Command_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_Command_Kill {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_Command_Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_Command_Save {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_Command_Topmost {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_Command_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   折り返し表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_Command_WordWrap {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_Command_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了コード: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_ExitCode {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_ExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行中 ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_Running {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準入出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_StandardInputOutput_Header {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_StandardInputOutput_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_StandardInputOutput_StandardInputOutput_Send {
            get {
                return ResourceManager.GetString("String_StandardInputOutput_StandardInputOutput_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Startup_Caption {
            get {
                return ResourceManager.GetString("String_Startup_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラム自動取り込み(_P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Startup_Command_ImportPrograms {
            get {
                return ResourceManager.GetString("String_Startup_Command_ImportPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知領域設定(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Startup_Command_NotifyArea {
            get {
                return ResourceManager.GetString("String_Startup_Command_NotifyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップ登録(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Startup_Command_RegisterStartup {
            get {
                return ResourceManager.GetString("String_Startup_Command_RegisterStartup", resourceCulture);
            }
        }
    }
}
