//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentTypeTextNet.Pe.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentTypeTextNet.Pe.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SyntaxDefinition xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot; name=&quot;EnvVar_Update&quot;&gt;
        ///	&lt;!--TODO:キーと値で分離--&gt;
        ///	&lt;Color name=&quot;Key&quot; fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot; /&gt;
        ///	&lt;Color name=&quot;Variable&quot; foreground=&quot;Maroon&quot; /&gt;
        ///	&lt;RuleSet ignoreCase=&quot;true&quot;&gt;
        ///		&lt;Rule color=&quot;Key&quot;&gt;
        ///			\w+
        ///		&lt;/Rule&gt;
        ///	&lt;/RuleSet&gt;
        ///&lt;/SyntaxDefinition&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_Highlighting_EnvironmentVariable_Merge {
            get {
                return ResourceManager.GetString("File_Highlighting_EnvironmentVariable_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SyntaxDefinition xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot; name=&quot;EnvVar_Remove&quot;&gt;
        ///	&lt;!--TODO:キーに限定--&gt;
        ///	&lt;Color name=&quot;Key&quot; fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot; /&gt;
        ///	&lt;RuleSet ignoreCase=&quot;true&quot;&gt;
        ///		&lt;Rule color=&quot;Key&quot;&gt;
        ///			\w+
        ///		&lt;/Rule&gt;
        ///	&lt;/RuleSet&gt;
        ///&lt;/SyntaxDefinition&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_Highlighting_EnvironmentVariable_Remove {
            get {
                return ResourceManager.GetString("File_Highlighting_EnvironmentVariable_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SyntaxDefinition xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot; name=&quot;EnvVar_Remove&quot;&gt;
        ///	&lt;!--きちんとする--&gt;
        ///	&lt;Color name=&quot;Key&quot; /&gt;
        ///	&lt;RuleSet ignoreCase=&quot;true&quot;&gt;
        ///		&lt;Rule color=&quot;Key&quot;&gt;
        ///			\w+
        ///		&lt;/Rule&gt;
        ///	&lt;/RuleSet&gt;
        ///
        ///&lt;/SyntaxDefinition&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File_Highlighting_Tag {
            get {
                return ResourceManager.GetString("File_Highlighting_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動設定グループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherGroup_ImportItem_Name {
            get {
                return ResourceManager.GetString("String_LauncherGroup_ImportItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいグループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherGroup_NewItem_Name {
            get {
                return ResourceManager.GetString("String_LauncherGroup_NewItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいアイテム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_LauncherItem_NewItem_Name {
            get {
                return ResourceManager.GetString("String_LauncherItem_NewItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_General_Header_Command {
            get {
                return ResourceManager.GetString("String_Setting_General_Header_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_General_Header_Execute {
            get {
                return ResourceManager.GetString("String_Setting_General_Header_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   general に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_General_Header_General {
            get {
                return ResourceManager.GetString("String_Setting_General_Header_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   note に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_General_Header_Note {
            get {
                return ResourceManager.GetString("String_Setting_General_Header_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   stdio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_General_Header_StandardInputOutput {
            get {
                return ResourceManager.GetString("String_Setting_General_Header_StandardInputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_General_Header_Update {
            get {
                return ResourceManager.GetString("String_Setting_General_Header_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_General_Header_Window {
            get {
                return ResourceManager.GetString("String_Setting_General_Header_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   general に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Header_General {
            get {
                return ResourceManager.GetString("String_Setting_Header_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   keyboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Header_Keyboard {
            get {
                return ResourceManager.GetString("String_Setting_Header_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   groups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Header_LauncherGroups {
            get {
                return ResourceManager.GetString("String_Setting_Header_LauncherGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Header_LauncherItems {
            get {
                return ResourceManager.GetString("String_Setting_Header_LauncherItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   toolbars に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Setting_Header_LauncherToolbars {
            get {
                return ResourceManager.GetString("String_Setting_Header_LauncherToolbars", resourceCulture);
            }
        }
    }
}
